### ISSUE TITLE
`저작권이 있는 토스페이스명` 문구에 관한 제안

### ISSUE THREAD

**Issue by combacsa** [toss/tossface#1]
안녕하세요. 먼저 토스팀이 토스페이스를 깃허브를 통해 공개하시는 모습을 보게 되어 반갑습니다. 라이센스 조항에 대해 두 가지 제안드립니다.

`‘저작권이 있는 토스페이스명’은 토스팀의 저작권 정책에 따라서 지정된 이름을 말합니다. `

현재 LICENSE 에는 위와 같은 표현이 등장합니다. OFL 라이센스의 경우 보통 본문 중에 `Reserved Font Name`에 관한 내용이 나오기 때문에 앞 부분에서 용어 정의에 그런 내용이 나옵니다. 하지만 현재 토스페이스 라이센스에는 해당 표현이 쓰이는 조항이 본조에서 삭제되었기 때문에, 정의에 이 표현이 남아있는 것이 다소 어색하게 느껴집니다.

보통 국내에서 다른 OFL 폰트들의 라이센스 번역에서 `저작권이 있는 폰트명`으로 번역되는 것이 굳이 `저작권이 있는 토스페이스명`이라고 적혀있는 것도 다소 어색하게 느껴집니다.

이에, 라이센스 본문 중에 `저작권이 있는 토스페이스명`이 없으니 차라리 용어 정의 항목에서도 해당 사항을 빼 주시는 것이 어떨지 제안드립니다.

또한, 토스팀에서 OFL 을 참고하시어 토스페이스 라이센스를 작성하셨다는 것을 알 수 있게 해 주시면 좋을 듯합니다. 오픈 소스 생태계에서 앞선 작업자들이 이런 노력을 기울였고 이를 토스팀 또한 존중한다는 것을 알리는 데도 의미있을 듯 합니다. 

읽어주셔서 고맙습니다.

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심 가져주셔서 감사합니다.

@combacsa 님께서 제안해주신 내용을 바탕으로 토스팀 내부에서 논의해, 해당 부분을 반영하여 라이선스 본문을 빠르게 수정하고 토스페이스 홈페이지와 저장소 `LICENSE`에 반영할 예정입니다.

라이선스와 관련해 좋은 의견 주셔서 정말 감사드립니다. 🙇

**Comment by sudosubin** [comment]
https://github.com/toss/tossface/commit/b2d0ea45222500da0f8c9784f4be18afd9f2eacd 에서 제보해주신 내용이 수정되어서 본 이슈는 close 하도록 하겠습니다. 🙇
