### ISSUE TITLE
파이널컷 프로 지원

### ISSUE THREAD

**Issue by danceglass** [toss/tossface#10]
안녕하세요 개발자님! Tossface를 파이널컷에서 사용하고 싶어하는 영상제작자 1인 입니다.
Tossfece를 영상편집에서도 자유로이 사용하고 싶은데 파이널컷 프로에서는 정상적으로 이모지가 보이질 않습니다 ㅜㅜ
도움 부탁드립니다!

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심을 가져주셔서 감사합니다.

혹시 파이널컷 프로그램에서 토스페이스 이모지가 어떻게 보이지 않는지, 조금 더 자세한 상황을 말씀해주실 수 있을까요? 스크린샷을 함께 첨부해주시면 문제 상황을 확인하기 더 쉬울 것 같습니다.

감사합니다 :)

**Comment by danceglass** [comment]
<img width="625" alt="스크린샷 2023-04-21 오후 12 25 26" src="https://user-images.githubusercontent.com/17689691/233533869-b2a79e8d-d9a6-4f3f-b14d-9713e9fa70f8.png">

오른쪽 설정창에서는 정상적으로 보이는듯 하나, 실제 화면속에서는 투명하게 표시되어집니다

**Comment by sudosubin** [comment]
안녕하세요 @danceglass 님.

토스 팀 내에서 Final Cut Pro 테스트를 진행했는데, 제보해주신 것처럼 토스페이스를 이용할 수 없는 것을 확인했습니다 😢 
일반적인 macOS 소프트웨어는 sbix 테이블의 컬러 폰트들을 지원하는데, 테스트해보니 Final Cut Pro의 경우 sbix 테이블의 다른 폰트들도 지원하지 않는 것으로 보입니다.

현재 Final Cut Pro에서는 토스페이스의 svg 풀셋은 활용하실 수 있어서, 필요하신 경우 svg 파일을 이용해보셔도 좋을 것 같습니다. 그 외에도, 토스페이스의 다음 버전에서 Final Cut Pro를 지원할 수 있을지 확인해보겠습니다.

토스페이스에 관심을 갖고 이슈를 제보해주셔서 감사드립니다 :)
