### ISSUE TITLE
SVG 파일 누락

### ISSUE THREAD

**Issue by JeukHwang** [toss/tossface#12]
Tossface를 이용한 프로젝트를 진행하는 과정에서 다음과 같은 사실을 알게 되어 공유합니다.

https://www.emojiall.com/ko/all-emojis 의 자료와 Tossface 저장소에 올라온 SVG 파일을 비교하는 과정에서,
일부 character에 대한 SVG가 누락되었음을 알게되었습니다.
제가 찾아낸 character는 다음과 같이 정리하였으며 제가 찾지 못한 추가 누락 character가 존재할 수도 있습니다.
https://gist.github.com/JeukHwang/003bad2ed5bcf6d0acd7f1bf0b45f5aa

추가적으로 `\u{FE0F}`과 `\u{FE0E}`에 따른 차이점이 생기는 것을 지양하시는 듯합니다.
이에 따라 SVG 파일들에서 보이듯이 `numbersign, asterisk, 0-9`를 제외한 character에 대해서는 `\u{FE0F}`과 `\u{FE0E}`를 아예 포함하지 않는 정책을 가지고 계신 것 같습니다.
그런데 다음 두 경우에는 `\u{FE0F}`가 사용된 특별한 이유가 있는지 궁금합니다.
https://github.com/toss/tossface/blob/main/dist/svg/u26F9_uFE0F_u200D_u2640.svg
https://github.com/toss/tossface/blob/main/dist/svg/u26F9_uFE0F_u200D_u2642.svg

참고로 저는 `\u{FE0F}`과 `\u{FE0E}`에 대해서 https://stackoverflow.com/questions/38100329/what-does-u-ufe0f-in-an-emoji-mean-is-it-the-same-if-i-delete-it 을 참고하였습니다.

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심 가져주셔서 감사합니다 :)

첫 번째로, Unicode 14.0의 신규 Glyph 중 일부가 ttf/woff/woff2 폰트 파일에는 존재하지만, svg 파일에서는 누락된 것을 확인했습니다. 누락된 Glyph들은 곧 릴리즈 될 Tossface v1.5를 통해 추가될 예정입니다.

두 번째로, 토스페이스에서는 확인해주신 내용처럼 `uFE0F`를 사용하지 않고 있습니다. svg 파일명에서 `uFE0F`를 제거하는 과정 중에 일부 svg 파일이 누락되었던 것으로 보이고, 해당 파일들도 Tossface v1.5를 통해 수정될 예정입니다.

토스페이스에 많은 관심을 갖고 이러한 점들을 꼼꼼히 제보해주셔서 정말 감사드립니다.
Tossface v1.5가 릴리즈 되면 다시 찾아오겠습니다 😄

**Comment by sudosubin** [comment]
안녕하세요, 현재 토스페이스 [v1.5](https://github.com/toss/tossface/releases/tag/v1.5)에서 본 이슈의 문제가 수정되어, 사용하실 수 있습니다.

추가로 토스페이스 이용에 문제가 있다면 말씀 부탁드립니다. 앞으로도 토스페이스에 많은 관심 부탁드립니다 🙇

**Comment by JeukHwang** [comment]
멋진 폰트 만들어주셔서 감사드립니다 :)
