### ISSUE TITLE
버전 릴리즈시 이슈 라이징 링크 추가 요청

### ISSUE THREAD

**Issue by bhyoo99** [toss/tossface#16]
안녕하세요 토스 페이스를 만들어 주시는 디자인/개발자 여러분
다시한번 이렇게 멋진 이모지를 만들어주셔서 감사의 인사 먼저 드립니다 :)

다름 아니라 이번에 토스페이스 홈페이지 업데이트에
![image](https://github.com/toss/tossface/assets/62757768/5c806450-05ce-4c43-a421-04acf0955339)
오픈소스와 지속적인 업데이트를 강점으로 소개해 주셨더라구요!

한국에 이렇게 크게 이모지 오픈소스 프로젝트가 없었다보니, 이런 멋진 프로젝트에 의견과 이슈를 남길 수 있어 영광입니다.

개인적으로 토스페이스 프로젝트에 관심이 많다보니, 지금까지 11개의 클로즈 이슈에 2개를 라이징 해봤는데요,\
https://github.com/toss/tossface/issues/5
https://github.com/toss/tossface/issues/11

가능하다면 더 많은 오픈소스 참여자와 건전한 이슈 문화를 만들기 위해,
**향후 업데이트 릴리즈 노트에는 해당 의견의 이슈를 참조하여, 같이 공개**되면 좋겠습니다.

만약 같이 공개 또는 언급이 된다면, 이슈를 개선한 배경이 무엇이며, 다른 분들도 업데이트 릴리즈 노트를 볼 때 왜 업데이트 되었는지 더욱 명확하게 확인 하실 수 있을 것 같습니다 :)

물론 작업하실 부분이 더 추가되지만, 커뮤니티가 만들어가는 프로젝트로 발전한다면 더 큰 토끼를 잡을 수 있다고 생각합니다.

위 내용으로 의견 주시면 감사하겠습니다 :)

**Comment by sudosubin** [comment]
안녕하세요, 토스페이스에 관심 가져주셔서 감사합니다 :)

먼저 지속적으로 토스페이스에 관심을 갖고 이슈를 남겨주셔서 정말 감사드립니다. 오픈소스 프로젝트의 발전에 커뮤니티의 참여는 빠질 수 없는데, 소중한 의견을 남겨주시는 참여자분들을 통해서 토스페이스 프로젝트가 지금까지 발전할 수 있었던 것 같습니다. 🙇 

현재까지는 GitHub Release에 변경된 내용을 위주로 작성했지만, 앞으로는 Release에 변경하게 된 이유도 함께 제공하고, 그 변경 사항이 이슈를 기반으로 하는 경우에는 이슈 링크도 함께 포함하고자 합니다.

이를 통해서 @bhyoo99 님의 말씀처럼 토스페이스 기여 문화가 더 활성화되고 개선되면 좋겠습니다 :)

그동안 소중한 이슈 남겨주셔서 정말 감사드리며, 앞으로도 토스페이스에 많은 관심 가져주시면 감사하겠습니다. 🙇
