### ISSUE TITLE
COLR 포맷의 폰트의 배포계획이 있나요?

### ISSUE THREAD

**Issue by HelloWorld017** [toss/tossface#18]
안녕하세요! 다름이 아니라 토스페이스의 폰트 용량이 큰 것 같아 테이블 덤프를 하던 중, 비트맵을 저장하는 `sbix` 테이블이 사용되고 있는 것을 확인할 수 있었습니다. 참고로 `sbix` 테이블은 구글크롬에서는 정상적으로 동작하나, 파이어폭스에서는 제대로 동작하지 않으며 (정확히는 특정 플랫폼에서만 동작합니다) 폰트 전체의 큰 용량으로 이어질 수 있습니다.

확인해본 결과, 토스페이스 공식 홈페이지에서는 `colr` 테이블을 사용한 `TossFaceFontWeb.otf` 를 사용하는 것으로 보이는데, 혹시 이 파일은 현재 레포지토리에 배포될 계획이 없을까요?

감사합니다!

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심 가져주셔서 감사합니다 :)

컬러 폰트는 폰트 포맷(`ttf`, `otf`, `woff`)과 컬러 테이블(`sbix`, `colr`)가 각각 쌍으로 브라우저에 잘 구현되어있어야 동작합니다. 많은 브라우저들에서 `otf` ↔ `colr`는 잘 구현되어 있지만, `woff2` ↔ `colr`는 구현이 누락된 경우가 있었습니다 😢 

이모지 폰트가 글로벌에서도 사례가 많지 않은 경우이다보니, 스펙이 브라우저에서 확인이 잘 안 되어있는 경우가 있습니다. 가장 최근에는 iOS 17 Safari에서 `woff2` ↔ `colr`가 구현되어 있다고 알려졌지만, [실제로는 동작하지 않았던 경우](https://developer.apple.com/forums/thread/740180)도 있었습니다.

Tossface는 말씀해주신 것처럼 현재 홈페이지에서 제공되는 `otf` 파일은 다른 브라우저에서도 `colr` 포맷을 잘 지원하는 포맷이고, 우선 해당 파일을 [toss/tossface@v1.6.1](https://github.com/toss/tossface/tree/v1.6.1)에 반영해두었습니다. 추후 릴리즈에서는 `colr`과 `otf` 지원을 포함하는 `css`, `subset`을 추가해 반영할 예정입니다.

이슈가 브라우저마다, 그리고 폰트 포맷과 컬러 테이블마다 파현화되어 있다보니 간단한 방법으로는 해결이 어려울 것 같고, 앞으로도 지속적으로 확인하며 개선하도록 하겠습니다 :D

좋은 의견 제안해주셔서 감사드립니다. 🙇
