### ISSUE TITLE
toss.im/tossface 페이지 '지금 써볼까요?' 기능 일부 이모지 표시 오류

### ISSUE THREAD

**Issue by min-uuu** [toss/tossface#2]
안녕하세요 토스페이스를 애정하는 사용자입니다.
리뉴얼된 toss.im/tossface 페이지의 '지금 써볼까요?' 기능에 일부 이모지 표시 오류가 있어 이슈 남깁니다.

<img width="1654" alt="Screen Shot 2022-04-05 at 11 44 33 AM" src="https://user-images.githubusercontent.com/63281188/161668893-4f3c2648-dfaf-43ad-a520-50e0ee8e3c1f.png">

위 사진처럼 일부 이모지는 토스페이스 이모지가 아닌 Mac OS의 기본 이모지로 표시가 되고 있습니다.

다음은 약 30개의 이모지 입력 테스트를 통해 확인된 토스페이스 이모지로 대체되지 않고 있는 이모지 목록입니다.
- 🥹
- 🫡
- 🫢
- 🫣

테스트 환경
- Mac OS 12.3.1
- Google Chrome Version 100.0.4896.60 (Official Build) (x86_64)

**Comment by Gijuno** [comment]
테스트 환경

- Mac OS 12.3.1
- Google Chrome Version 100.0.4896.60 (Official Build) (x86_64)

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심 가져주셔서 감사합니다.

현재 토스페이스 v1.1에서는 `README.md`의 내용과 같이 Unicode v13.1의 이모지 전체를 제공하고 있는데요,

@min-uuu 님, @Gijuno 님께서 제보해주신 아래 이모지들은 Unicode v14.0에 추가된 이모지들로, 현재 토스페이스 v1.1에서는 지원하지 않고 있습니다.

- 🥹: [U+1F979](https://unicode.org/emoji/charts/emoji-released.html#1f979)
- 🫡: [U+1FAE1](https://unicode.org/emoji/charts/emoji-released.html#1fae1)
- 🫢: [U+1FAE2](https://unicode.org/emoji/charts/emoji-released.html#1fae2)
- 🫣: [U+1FAE3](https://unicode.org/emoji/charts/emoji-released.html#1fae3)
- 🫠: [U+1FAE0](https://unicode.org/emoji/charts/emoji-released.html#1fae0)
- 🫥: [U+1FAE5](https://unicode.org/emoji/charts/emoji-released.html#1fae5)
- 🫶: [U+1FAF6](https://unicode.org/emoji/charts/emoji-released.html#1faf6)

하지만 토스페이스의 다음 버전에서 Unicode v14.0 지원을 추가할 계획이고, 토스페이스 v1.2에서 업데이트 될 예정입니다.

이모지 지원에 대해 제보해주셔서 정말 감사드립니다. 🙇

**Comment by sudosubin** [comment]
안녕하세요, 토스페이스 [`v1.3`](https://github.com/toss/tossface/releases/tag/v1.3)에서 아래 이미지와 같이 Unicode v14.0 지원이 추가되었습니다. 감사드립니다 🙇 

<img width="876" alt="image" src="https://user-images.githubusercontent.com/32478597/184852648-bf5604b1-1de6-4a06-a685-513fb9c6050a.png">

**Comment by Gijuno** [comment]
@sudosubin 
반영 감사드립니다! 앞으로 토스페이스 더 자주 애용하겠습니다 😎😎

**Comment by min-uuu** [comment]
@sudosubin 끝까지 힘써주셔서 감사합니다!
항상 응원하겠습니다 😎
