### ISSUE TITLE
토스페이스 폰트 설정 값 수정 제안 및 라이선스 관련 질문

### ISSUE THREAD

**Issue by 0w0i0n0g0** [toss/tossface#3]
안녕하세요! 토스페이스를 여기저기 적용시켜보는 중인 한 사용자입니다.

현재 토스페이스의 descender 값이 -300으로 설정되어 있어 다른 폰트와 섞여있을 때 토스페이스 이모지들만 위로 툭 튀어나와 있는 현상이 있습니다.

이번에 간단한 vscode 테마 확장을 토스페이스를 활용해 제작해보려고 하는데 이 값 때문에 제대로 정렬이 되지 않습니다.

그래서 폰트 파일의 hhea[(참고 링크)](https://docs.microsoft.com/en-us/typography/opentype/spec/hhea) 속성 중 **descender가 0으로 수정**되었으면 합니다.
<br>

다만 토스페이스가 추구하는 방향이 있고, 모든 사용자가 이런 수정을 원하지는 않을 수 있기 때문에, 

#### 허용되지 않는다면 해당 값을 수정하여, 텍스트 베이스라인에 딱 붙어있는 버전의 토스페이스를 추가로 배포하실 계획이 있으신지도 궁금합니다.

<br>
읽어주셔서 감사합니다.😉

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심 가져주셔서 감사합니다.

토스페이스의 descender 값을 0으로 조정할 경우, Microsoft Office 등의 일부 앱에서 베이스 라인 아래 부분이 잘려 보이기 때문에 현재는 -300으로 설정되어 있습니다. 그리고 이모지의 위치는 ascender, descender 등 다양한 값에 영향을 받아 descender 값을 0으로 설정하더라도 이모지의 위치는 내려가지 않고, 오히려 안드로이드 계열에서 이모지가 더 위로 올라갈 수도 있습니다.

이모지 폰트의 상하 위치는 운영체제, 앱마다 다르게 나타나고, 함께 사용하는 폰트에 따라서도 달라집니다. 현재 토스페이스는 토스 프로덕트 산스와의 위치를 고려하며 디자인되었고, 상하 위치를 별도로 조정할 계획은 없는 상태입니다. 다만, @0w0i0n0g0 님께서 문제를 겪고 계신 운영체제와 앱, 함께 사용 중이신 폰트 등의 정보를 공유해주시면 추가로 더 확인해볼 수 있을 것 같습니다 :)

더불어, 토스팀은 토스페이스의 폰트 파일을 어떤 방식으로든 수정·변형하여 사용하거나 배포하는 것에 대해 토스페이스 저작권 안내 및 라이선스를 위반하는 것으로 허용하지 않고 있습니다.

기술적으로 좋은 피드백 주셔서 정말 감사드립니다. 🙇

**Comment by sudosubin** [comment]
안녕하세요, 현재 배포 중인 토스페이스 폰트(`TossFaceFontMac.ttf`)는 Mac용 폰트로, Mac 환경에서 사용하는 Adobe, MS Office, Keynote 등의 프로그램에서 잘 보여지도록 만들어졌습니다.

따라서 @Sunnynah 님이 제보해주신 iOS 환경, 또는 다른 Android 등의 다른 환경에서는 제대로 동작하지 않을 수 있습니다 :pray:

iOS 환경에 대해 제보해주셔서 감사드립니다. 🙇
또 다른 Mac 환경에서도 이슈가 발생한다면 제보해주시면 감사하겠습니다.
