### ISSUE TITLE
유니코드 Private Use Area를 이용해 한국적, 시대적 가치를 담은 이모지 재배포

### ISSUE THREAD

**Issue by anaclumos** [toss/tossface#4]
<img src="https://user-images.githubusercontent.com/31657298/167289609-1804c8de-df31-4f9b-820e-33584cae0bd8.PNG" width="300" align="right">

Unicode [Private Use Area](https://en.wikipedia.org/wiki/Private_Use_Areas#:~:text=In%20Unicode%2C%20a%20Private%20Use,characters%20by%20the%20Unicode%20Consortium.)를 이용해 기존의

1. 한국적 가치를 담은 이모지(예: 막걸리) 그리고
2. 시대적 가치를 담은 이모지(예: 푸시 알림)를

재배포하는 방안을 제안합니다.

Private Use Area는 유니코드 컨소티움에서 제삼자가 자유롭게 사용할 수 있도록 풀어준 영역으로 기존에 제기된 문제들이 발생하지 않을 것입니다. 

> [Private Use Areas] are intentionally left undefined so that third parties may define their own characters without conflicting with Unicode Consortium assignments. [Wikipedia]

- 토스페이스는 한국적이고 현대적인 가치를 잘 정립하여 멋스럽고 정다운 형태로 이모지를 녹여냈기에 이렇게 "유니코드의 표의와 맞지 않다"는 가벼운 이유 만으로 사라지기에는 너무 아깝습니다.
- 본래 이런 목적으로 사용하라고 제공한 공간이 존재하는 바, 이를 사용하여 본래 의도한 한국적, 현대적 가치를 재구현하면 어떻겠습니까?
- 유니코드 컨소티움이 Private Use Area를 제정한 목적과 토스페이스의 새로운 시도들의 방향성이 합치하기에 이렇게 공식적인 채널로 제안 드립니다.

항상 건강하시기 바랍니다.

감사합니다.

**Comment by anaclumos** [comment]
예시로  ← 애플 아이콘도 Private Use Area에 존재합니다.

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심 가져주셔서 감사합니다.

Unicode PUA(Private Use Areas)가 새로운 시도를 만들고자 했던 저희의 의도를 표현하기에 적합한 영역이라는 의견에 크게 공감합니다. 현재 토스팀 내에서 토스페이스의 다음 버전에 Unicode PUA를 이용해 일부 이모지를 포함하는 것을 적극적으로 검토하고 있습니다 :)

토스페이스의 Unicode PUA 지원과 관련해 좋은 의견 주셔서 정말 감사드립니다 🙇

**Comment by anaclumos** [comment]
안녕하세요. 해당 이슈를 작성한지 두 달 정도 지났는데, 혹시 추가적인 진전 사항이 있을까요?

**Comment by anaclumos** [comment]
@sudosubin 안녕하세요, 혹시 현재 올라온 GitHub 및 JSDelivr에 올라온 Tossface 파일의 U+E10A부터 U+E117 영역에 배포된 것이 맞을까요? 폰트가 렌더링되지 않아 여쭤봅니다.

**Comment by sudosubin** [comment]
안녕하세요, 현재 JSDelivr 및 GitHub dist에 업로드된 토스페이스 폰트 파일에는 PUA 영역의 폰트가 정상적으로 포함되어, 아래와 같이 이용이 가능합니다.

혹시 문제를 겪고 계신 환경의 자세한 내용이나 스크린샷 등을 공유해주실 수 있을까요?

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/32478597/185527102-1ff61b1e-e1e3-45dd-be88-94c1f0483075.png">

**Comment by anaclumos** [comment]
서버에 캐시된 파일 문제임을 확인했습니다. 이제 정상적으로 사용할 수 있습니다. 질문이 한 가지 있는데, 다음 이모지는 무엇을 나타내는 이모지인가요? 

<img width="208" alt="image" src="https://user-images.githubusercontent.com/31657298/185717917-441bb5aa-1504-4374-92cc-893ca730dba7.png">

**Comment by anaclumos** [comment]
그리고 "한국 우체국"과 같이 이번 배포에 빠져있는 이모지들이 있는 것 같은데 이 이모지들도 추후에 배포가 될 예정일까요?

**Comment by sudosubin** [comment]
안녕하세요 @anaclumos 님, 올려주신 질문에 대해 조금 늦게 답변 드립니다 :)

> 서버에 캐시된 파일 문제임을 확인했습니다. 이제 정상적으로 사용할 수 있습니다. 질문이 한 가지 있는데, 다음 이모지는 무엇을 나타내는 이모지인가요?

해당 이모지는 [토스플레이스](https://tossplace.com/)의 결제 단말기(POS)를 상징하는 이모지입니다.

> 그리고 "한국 우체국"과 같이 이번 배포에 빠져있는 이모지들이 있는 것 같은데 이 이모지들도 추후에 배포가 될 예정일까요?

제안해주신 한국 우체국 이모지는 토스페이스 다음 버전 릴리즈에 포함될 예정입니다. 혹시 누락된 다른 이모지가 또 있다면, 본 이슈에 함께 남겨주시면 확인 후 다음 버전 릴리즈에 추가하겠습니다 :)

토스페이스에 관심 가져주셔서 감사드리며, 앞으로도 토스페이스에 많은 관심 부탁드립니다 🙇
