### ISSUE TITLE
특정 이모지 디테일 수정 건의

### ISSUE THREAD

**Issue by bhyoo99** [toss/tossface#5]
안녕하세요 토스페이스 개발자/디자이너 여러분
먼저 좋은 이모지 리소스 제공해주셔서 너무 감사합니다! 

다름 아니라 🙏 Folded Hands 이모지 관련해서 의견을 드리고 싶어서 이슈로 만들었습니다.

사실 이 이모지의 본 목적은 "하이파이브를 하는 2명의 인물" 이지만, 
많은 커뮤니티 그리고 emoji 설명에서도 합장 또는 기도의 손 모양으로도 사용하는 것이 사실입니다.

관련 자료들은 
https://blog.emojipedia.org/emojiology-folded-hands/
https://emojipedia.org/folded-hands/
많은 곳에서 찾을 수 있습니다.

![image](https://user-images.githubusercontent.com/62757768/190853737-c7db5400-e2f2-4f6a-9a02-93c18ab916fa.png)
현재 토스페이스 이모지 입니다.

위 사용성을 포함하고, 원 의미인 "하이파이브 하는 순간"의 의미에서도 양 손바닥 사이에 있는 여백을 없엔 디자인이 더 적절할 것 같습니다.

토스페이스의 내부 디자인 규칙에 영향이 없다면 수정해주시면 매우 감사하겠습니다 :)

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심 가져주셔서 감사합니다.

@bhyoo99 님께서 제안해주신 내용을 바탕으로, 토스페이스 다음 버전에서 🙏 (Folded Hands) 이모지의 디자인 디테일을 다시 살펴보겠습니다.

이모지의 디테일과 관련해 좋은 의견 주셔서 정말 감사드립니다. 🙇

**Comment by bhyoo99** [comment]
@sudosubin 
먼저 빠른 답변 주심에 정말 감사합니다. 

위 이슈가 아니더라도 지속적으로 좋은 리소스 업데이트 해주셔서 감사드리며 더 애용하도록 하겠습니다 🙇
