### ISSUE TITLE
Tossface svg 파일 사용 문의

### ISSUE THREAD

**Issue by ojj1123** [toss/tossface#8]
안녕하세요.

tossface를 사이드프로젝트에 사용하려고 하는 이용자입니다.

tossface 이모지를 폰트파일(`.ttf`)이 아닌 `svg` 파일로 이용가능한지 문의드립니다.

> ‘수정본’은 포맷의 변경이나 토스페이스를 새로운 운영체제에 맞추어 변경하거나, 원본의 일부 혹은 전체에 추가, 삭제 대체해 만든 2차적 저작물을 의미합니다.
> 
> 허가 및 조건
> 1) 토스페이스는 그 자체를 판매하거나, 부정한 목적으로 이용하거나, 허용되지 않은 수정본을 만들지 않는 한 자유롭게 사용, 연구, 재배포 하실 수 있습니다.  
> 
> [LICENSE](https://github.com/toss/tossface/blob/main/LICENSE) 중

폰트(`.ttf`)가 아닌 `svg` 로 이용하고자 하는 이유는 tossface 폰트 중 극히 일부만 사용하기 때문에 용량이 더 적은 필요한 `svg` 만 골라서 사용하려고 합니다. 이모지의 본래 모양 자체에는 변형을 가하지 않을거고 이모지 크기(`size`) 값만 필요에 따라 변형하려고 합니다.

위 라이센스에 위반되는지 알려주시면 감사하겠습니다 🙂

**Comment by sudosubin** [comment]
안녕하세요, 먼저 토스페이스에 관심 가져주셔서 감사합니다.

@ojj1123 님께서 말씀해주신 내용은 토스페이스 라이선스에 위반되지 않는 사항으로, 토스페이스의 크기만 조절하여 사용하시는 경우 문제 없이 이용하실 수 있습니다.

라이선스와 관련해 먼저 문의 남겨주셔서 감사드리고, 앞으로도 많이 이용해주시면 감사하겠습니다. :bow:
